### ISSUE TITLE
ModuleNotFoundError: No module named 'xmltodict'

### ISSUE THREAD

**Issue by masroorz** [s4d0l1n/pyNetworkScan#1]
python3 pyNetworkScan.py -x outputscan.xml -i 10.128.128.0-256 -o timmy_stjoseph.json
Traceback (most recent call last):
  File "/home/students/Documents/joel/pyNetworkScan.py", line 1, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'

**Comment by s4d0l1n** [comment]
You need to settle the dependencies first
